# Generated by Django 6.0.3 on 2026-03-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFacultad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultad',
            name='ubicacion',
            field=models.CharField(default='Desconocida', max_length=100),
            preserve_default=False,
        ),
    ]
